### ISSUE TITLE
Circular inclusion leads to an uncaught RangeError

### ISSUE THREAD

**Issue by paulloz** [inkle/inky#132]
Ok, I really don't know if it's an issue because I suppose there is some kind of protection against this in during compilation but this breaks Inky a bit.

Let's say I create a `test.ink` file containing
```
INCLUDE test2.ink
```
And a `test2.ink` file containing
```
INCLUDE test.ink
```
Now Inky is broken.
Here's the sidebar
![image](https://user-images.githubusercontent.com/437025/34470961-024de19a-ef3d-11e7-8702-0581fac2197d.png)
And here's what happens whenever I try and type on my keyboard.
![image](https://user-images.githubusercontent.com/437025/34470977-290ae6d4-ef3d-11e7-80d8-20b472ae6ce2.png)

Error transcript:
```
Uncaught RangeError: Maximum call stack size exceeded
    at InkProject.inkFileWithRelativePath (/home/paulloz/Documents/inky/app/renderer/inkProject.js:480:14)
    at inkFile.includes.forEach.incPath (/home/paulloz/Documents/inky/app/renderer/inkProject.js:106:39)
    at Array.forEach (native)
    at addIncludePathsFromFile (/home/paulloz/Documents/inky/app/renderer/inkProject.js:103:26)
    at inkFile.includes.forEach.incPath (/home/paulloz/Documents/inky/app/renderer/inkProject.js:108:17)
    at Array.forEach (native)
    at addIncludePathsFromFile (/home/paulloz/Documents/inky/app/renderer/inkProject.js:103:26)
    at inkFile.includes.forEach.incPath (/home/paulloz/Documents/inky/app/renderer/inkProject.js:108:17)
    at Array.forEach (native)
    at addIncludePathsFromFile (/home/paulloz/Documents/inky/app/renderer/inkProject.js:103:26)
```

**Comment by Paulloz** [comment]
Oops, sorry I just saw it's a duplicate from #110.
