### ISSUE TITLE
[crash report]: nullreference on logic line

### ISSUE THREAD

**Issue by facelesspanda** [inkle/inky#194]
Input:
```
~ VAR y = 0
~ temp x = some_func(y)
{x}

=== function some_func(x) ==
hello
~ return x + 1
```

Stack trace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ink.InkParser.LogicLine()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.OneOf(ParseRule[] array)
   at Ink.InkParser.StatementAtLevel(StatementLevel level)
   at Ink.InkParser.<>c__DisplayClass134_0.b__0()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.Interleave[T](ParseRule ruleA, ParseRule ruleB, ParseRule untilTerminator, Boolean flatten)
   at Ink.InkParser.StatementsAtLevel(StatementLevel level)
   at Ink.InkParser.Parse()
   at Ink.Compiler.Compile()
   at Ink.CommandLineTool..ctor(String[] args)
   at Ink.CommandLineTool.Main(String[] args)
```

Probably on line 1 but it's hard to tell.

**Comment by joethephish** [comment]
Not reproducing in latest master, and this rings a bell - I must've fixed it a while ago. Should really do an ink release soon! Thanks for the report anyway :)
