### ISSUE TITLE
Inky 0.3.1 linux release does not work

### ISSUE THREAD

**Issue by Kilian** [inkle/inky#30]
When launching the linux download from the releases page, I get the following error: (Ubuntu 64 bit 16.04) 

```
[kilian:~/apps/Inky-linux-x64]$ ./Inky 
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1253:7)
    at Object.<anonymous> (/home/kilian/apps/Inky-linux-x64/resources/app.asar/main-process/inklecate.js:34:79)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/kilian/apps/Inky-linux-x64/resources/app.asar/main-process/projectWindow.js:6:19)
```
the error seems to be in this line: https://github.com/inkle/inky/blob/master/app/main-process/inklecate.js#L34

**Comment by joethephish** [comment]
Thanks for the report. Since we don't have a Linux box internally, we'd appreciate a pull request from anyone who manages to fix it! Is it possible that `process.env.temp` is undefined in Linux, or certain distros?
