### ISSUE TITLE
Inklecate coredumping

### ISSUE THREAD

**Issue by txomon** [inkle/inky#414]
Error stack:

```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.IO.TextWriter..cctor()
   at System.IO.StreamWriter..ctor(System.IO.Stream, System.Text.Encoding, Int32, Boolean)
   at System.Console.CreateOutputWriter(System.IO.Stream)
   at System.Console+<>c.<get_Out>b__26_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Threading.LazyInitializer.EnsureInitialized[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Console.EnsureInitialized[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Func`1<System.__Canon>)
   at System.Console.get_Out()
   at System.Console.WriteLine(System.String)
   at Ink.CommandLineTool.ExitWithUsageInstructions()
   at Ink.CommandLineTool..ctor(System.String[])
   at Ink.CommandLineTool.Main(System.String[])

```

However I have all icu libraries:

```
$ find /usr/lib/libic*
/usr/lib/libical
/usr/lib/libical/ical-glib-src-generator
/usr/lib/libical-glib.so
/usr/lib/libical-glib.so.3
/usr/lib/libical-glib.so.3.0.14
/usr/lib/libical.so
/usr/lib/libical.so.3
/usr/lib/libical.so.3.0.14
/usr/lib/libical_cxx.so
/usr/lib/libical_cxx.so.3
/usr/lib/libical_cxx.so.3.0.14
/usr/lib/libicalss.so
/usr/lib/libicalss.so.3
/usr/lib/libicalss.so.3.0.14
/usr/lib/libicalss_cxx.so
/usr/lib/libicalss_cxx.so.3
/usr/lib/libicalss_cxx.so.3.0.14
/usr/lib/libicalvcal.so
/usr/lib/libicalvcal.so.3
/usr/lib/libicalvcal.so.3.0.14
/usr/lib/libicudata.so
/usr/lib/libicudata.so.71
/usr/lib/libicudata.so.71.1
/usr/lib/libicui18n.so
/usr/lib/libicui18n.so.71
/usr/lib/libicui18n.so.71.1
/usr/lib/libicuio.so
/usr/lib/libicuio.so.71
/usr/lib/libicuio.so.71.1
/usr/lib/libicutest.so
/usr/lib/libicutest.so.71
/usr/lib/libicutest.so.71.1
/usr/lib/libicutu.so
/usr/lib/libicutu.so.71
/usr/lib/libicutu.so.71.1
/usr/lib/libicuuc.so
/usr/lib/libicuuc.so.71
/usr/lib/libicuuc.so.71.1
```

**Comment by franzmondlichtmann** [comment]
I'm running the latest version of arch on a modern computer. 
I installed Inky for the first time. Getting the same errors like the original poster.
Of course I have ICU installed.

I tried setting the following commands, but nothing worked:
LD_LIBRARY_PATH=/usr/lib in .bashrc
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 in /etc/environment
,but maybe I'm doing something wrong.

**Comment by franzmondlichtmann** [comment]
As a workaround, I installed Inky as a Flatpak and it works this way.
But I would still prefer install native Inky.

**Comment by katzecase** [comment]
Same problem here.

**Comment by rovantiq** [comment]
Installing libicu50 from AUR fixed it for me.

**Comment by katzecase** [comment]
> Installing libicu50 from AUR fixed it for me.

That fixed mine too! Thanks!

**Comment by gatoyhs** [comment]
Hi, does anyone know if this works for Windows aswell?. Thank you
