### ISSUE TITLE
Compiler error: Couldn't find ICU package (Arch linux)

### ISSUE THREAD

**Issue by CodeAndGin** [inkle/inky#424]
Hiya, I just downloaded release 0.13.0, and when I open the app, the compiler instantly gives me this:

```
Ink compiler had an unexpected error ☹

Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
Ink compiler had an unexpected error ☹

   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CompareInfo..cctor()
   at System.String.EndsWith(System.String, System.StringComparison)
   at Ink.CommandLineTool..ctor(System.String[])
   at Ink.CommandLineTool.Main(System.String[])
Ink compiler had an unexpected error ☹

Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CompareInfo..cctor()
   at System.String.EndsWith(System.String, System.StringComparison)
   at Ink.CommandLineTool..ctor(System.String[])
   at Ink.CommandLineTool.Main(System.String[])
```

Am I missing a dependency or something? There arent really many clear instructions

**Comment by rovantiq** [comment]
It seems there was an update to ICU that messed up dotnet stuff in Arch, installing libicu50 from the AUR fixed it for me.

**Comment by RPG-Alex** [comment]
> Installing an earlier ICU version from the AUR ([icu70](https://aur.archlinux.org/packages/icu70)) fixed it for me.

Yeah, I specifically contacted the maintainer of the Inkly AUR and they have updated the dependency list to [icu68](https://aur.archlinux.org/packages/icu68). Until inkly gets patched for the current version of icu this should work, though it means installing an older version of icu.
