### ISSUE TITLE
story .js file doesn't open in itch.io

### ISSUE THREAD

**Issue by frostymountain** [inkle/inky#472]
My story .js file doesn't open when my game page is opened on itch.io. It will open if I click "restart" but not before. I've spent quite a bit of time on it with no success, and it seems to be an issue with the original file exported by the inkle editor with no modifications.

![Screenshot 2023-03-23 121046](https://user-images.githubusercontent.com/125073963/227325121-222149a1-c09c-41ec-a38a-6b251823296b.png)

this is the error message:

ink.js:1 Uncaught Error: this.previousPointer.Resolve() is null or undefined
    at O (ink.js:1:8761)
    at t.value (ink.js:1:73582)
    at ink.js:1:67576
    at e.value (ink.js:1:82858)
    at e.value (ink.js:1:67437)
    at ink.js:1:89848
    at e.value (ink.js:1:83766)
    at t.value (ink.js:1:89790)
    at ink.js:1:100181
    at e.value (ink.js:1:83766)

**Comment by frostymountain** [comment]
SharedArrayBuffer support solve this issue.
