### ISSUE TITLE
JavaScript error on launch 0.15.1 on macOS 15.5.

### ISSUE THREAD

**Issue by bryanrieger** [inkle/inky#513]
Upon launching the latest 0.15.1 release on macOS Sonoma 14.5 (on an M1 Pro) I'm presented with the following error:

**A JavaScript error occurred in the main process.**

Uncaught Exception:
Error: spawn Unknown system error -86
at ChildProcess.spawn (node:internal/child_process:421:11)
at spawn (node:child_process:776:9)
at compile (/Applications/Inky.app/Contents/Resources/app.asar/main-process/inklecate.js:88:25)
at IpcMainImpl.<anonymous> (/Applications/Inky.app/Contents/Resources/app.asar/main-process/inklecate.js:320:5)
at IpcMainImpl.emit (node:events:518:28)
at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82415)
at WebContents.emit (node:events:518:28)

**Comment by Radar4000** [comment]
We got the same error on M1 Air. We tried to run an older version (0.14.1). The program asked us to install Rosetta, and after installing that it works just fine. In the last two versions, it does not ask for the user to install Rosetta for some reason but after the Rosetta installation latest version (0.15.1) works fine.

**Comment by berkough** [comment]
I get the same error running the Linux version on Chrome OS.

**Comment by ahamelers** [comment]
I have this error with 0.15.1 on macOS 15.6

**A JavaScript error occurred in the main process**
```
Uncaught Exception:
Error: spawn Unknown system error -86
at ChildProcess.spawn (node:internal/child_process:421:11)
at spawn (node:child_process:776:9)
at compile (/Applications/Inky.app/Contents/Resources/app.asar/main-process/inklecate.js:88:25)
at IpcMainImpl.<anonymous> (/Applications/Inky.app/Contents/Resources/app.asar/main-process/inklecate.js:320:5)
at IpcMainImpl.emit (node:events:518:28)
at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82415)
at WebContents.emit (node:events:518:28)
```
