### ISSUE TITLE
Error: EPERM

### ISSUE THREAD

**Issue by shakna-israel** [inkle/inky#522]
Error: EPERM reported for directories I really wouldn't expect Inky to be watching, but apparently doesn't have permission for.

This breaks the web view, and export.

Platform: Windows 11 23H2 22631.4460
Inky version: 0.15.1
ink version: 1.2.0
inkjs version: 2.2.3

![Screenshot 2024-12-10 193922](https://github.com/user-attachments/assets/78a7a1d9-7c78-4484-97f9-64e056e7350f)

    node:internal/errors:563 Uncaught (in promise) Error: EPERM: operation not permitted, watch 'C:\Users\jmilne\Documents\My Music'
        at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
        at __node_internal_uvException (node:internal/errors:619:10)
        at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
        at Object.watch (node:fs:2473:36)
        at createFsWatchInstance (C:\Users\jmilne\Down…s-handler.js:119:15)
        at setFsWatchListener (C:\Users\jmilne\Down…s-handler.js:166:15)
        at NodeFsHandler._watchWithNodeFs (C:\Users\jmilne\Down…s-handler.js:331:14)
        at NodeFsHandler._handleDir (C:\Users\jmilne\Down…s-handler.js:567:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async NodeFsHandler._addToNodeFs (C:\Users\jmilne\Down…s-handler.js:617:16)
    node:internal/errors:563 Uncaught (in promise) Error: EPERM: operation not permitted, watch 'C:\Users\jmilne\Documents\My Pictures'
        at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
        at __node_internal_uvException (node:internal/errors:619:10)
        at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
        at Object.watch (node:fs:2473:36)
        at createFsWatchInstance (C:\Users\jmilne\Down…s-handler.js:119:15)
        at setFsWatchListener (C:\Users\jmilne\Down…s-handler.js:166:15)
        at NodeFsHandler._watchWithNodeFs (C:\Users\jmilne\Down…s-handler.js:331:14)
        at NodeFsHandler._handleDir (C:\Users\jmilne\Down…s-handler.js:567:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async NodeFsHandler._addToNodeFs (C:\Users\jmilne\Down…s-handler.js:617:16)
    node:internal/errors:563 Uncaught (in promise) Error: EPERM: operation not permitted, watch 'C:\Users\jmilne\Documents\My Videos'
        at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
        at __node_internal_uvException (node:internal/errors:619:10)
        at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
        at Object.watch (node:fs:2473:36)
        at createFsWatchInstance (C:\Users\jmilne\Down…s-handler.js:119:15)
        at setFsWatchListener (C:\Users\jmilne\Down…s-handler.js:166:15)
        at NodeFsHandler._watchWithNodeFs (C:\Users\jmilne\Down…s-handler.js:331:14)
        at NodeFsHandler._handleDir (C:\Users\jmilne\Down…s-handler.js:567:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async NodeFsHandler._addToNodeFs (C:\Users\jmilne\Down…s-handler.js:617:16)

The tiny in-progress story that triggered it, though I wouldn't expect it to be the root cause: [here](https://gist.github.com/shakna-israel/8d526eb5a97109e4d519607182419340).

**Comment by shakna-israel** [comment]
Seems like chokidar has had this issue a few times, always related to the Windows platform.

* [643](https://github.com/paulmillr/chokidar/issues/643)

* [566](https://github.com/paulmillr/chokidar/issues/566)

* [1380](https://github.com/paulmillr/chokidar/issues/1380)

In almost all cases, the only people saying they've resolved the issue have been people moving to a different dependency, which isn't exactly helpful.

**Comment by sebj8** [comment]
Absurd. It should check local folders like /assets/music /assets/videos etc... not user documents folders.
