### ISSUE TITLE
"Sorry, the ink compiler crashed"

### ISSUE THREAD

**Issue by alexanderww** [inkle/inky#68]
Hello!
I have some  problem when starting Inky, immediately after the start I have an error message in compiler window 

*Sorry, the ink compiler crashed ☹

Here is some diagnostic information:

Unhandled Exception: 
Ink compiler had an unexpected error ☹

System.Runtime.InteropServices.COMException: Invalid value for registry (Exception from HRESULT: 0x80040153 (REGDB_E_INVALIDVALUE))
   at System.Runtime.InteropServices.RuntimeEnvironment.GetDeveloperPath()
   at System.AppDomain.SetupFusionStore(AppDomainSetup info, AppDomainSetup oldInfo)
   at System.AppDomain.SetupDomain(Boolean allowRedirects, String path, String configFile, String[] propertyNames, String[] propertyValues)*

**Comment by joethephish** [comment]
Sorry to hear that! Looks like you're on Windows, is that right? Which version? Are you using 32 bit or 64 bit?

Is this version 0.6.2? Anyone else seeing this?

**Comment by zetaverse** [comment]
Hi, I am facing this issue on linux. Attaching a screenshot for reference.

OS is Xubuntu 17.04 (64 bit)

![selection_047](https://user-images.githubusercontent.com/3366237/29242376-e56d2f66-7fa9-11e7-9213-f78ad18a764b.png)

Would very helpful if you can help me sort this out. Thanks

**Comment by ghua78** [comment]
same problem on ubuntu linux 18.04, Inky 0.10.0

Unhandled Exception:
System.TypeLoadException: Could not load type 'Ink.InkParser' from assembly 'ink_compiler, Version=1.0.6801.18922, Culture=neutral, PublicKeyToken=null'.
  at Ink.CommandLineTool..ctor (System.String[] args) [0x001e4] in <1d6aa8dbdffc49d786fd371920909921>:0 
  at Ink.CommandLineTool.Main (System.String[] args) [0x00001] in <1d6aa8dbdffc49d786fd371920909921>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'Ink.InkParser' from assembly 'ink_compiler, Version=1.0.6801.18922, Culture=neutral, PublicKeyToken=null'.
  at Ink.CommandLineTool..ctor (System.String[] args) [0x001e4] in <1d6aa8dbdffc49d786fd371920909921>:0 
  at Ink.CommandLineTool.Main (System.String[] args) [0x00001] in <1d6aa8dbdffc49d786fd371920909921>:0

**Comment by zyq0825** [comment]
similar on window 64, inky 0.10.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ink.InkParser.LogicLine()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.OneOf(ParseRule[] array)
   at Ink.InkParser.StatementAtLevel(StatementLevel level)
   at Ink.InkParser.<>c__DisplayClass134_0.b__0()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.Interleave[T](ParseRule ruleA, ParseRule ruleB, ParseRule untilTerminator, Boolean flatten)
   at Ink.InkParser.StatementsAtLevel(StatementLevel level)
   at Ink.InkParser.InnerConditionalContent(Expression initialQueryExpression)
   at Ink.InkParser.<>c__DisplayClass119_0.b__0()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.Expect(ParseRule rule, String message, ParseRule recoveryRule)
   at Ink.InkParser.InnerLogic()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.Expect(ParseRule rule, String message, ParseRule recoveryRule)
   at Ink.InkParser.InlineLogic()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.OneOf(ParseRule[] array)
   at Ink.InkParser.InlineLogicOrGlue()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.<>c__DisplayClass55_0.b__0()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.Interleave[T](ParseRule ruleA, ParseRule ruleB, ParseRule untilTerminator, Boolean flatten)
   at Ink.InkParser.MixedTextAndLogic()
   at Ink.StringParser.Parse[T](SpecificParseRule`1 rule)
   at Ink.InkParser.LineOfMixedTextAndLogic()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.OneOf(ParseRule[] array)
   at Ink.InkParser.StatementAtLevel(StatementLevel level)
   at Ink.InkParser.<>c__DisplayClass134_0.b__0()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.Interleave[T](ParseRule ruleA, ParseRule ruleB, ParseRule untilTerminator, Boolean flatten)
   at Ink.InkParser.StatementsAtLevel(StatementLevel level)
   at Ink.InkParser.b__100_0()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.Expect(ParseRule rule, String message, ParseRule recoveryRule)
   at Ink.InkParser.KnotDefinition()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.OneOf(ParseRule[] array)
   at Ink.InkParser.StatementAtLevel(StatementLevel level)
   at Ink.InkParser.<>c__DisplayClass134_0.b__0()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.Interleave[T](ParseRule ruleA, ParseRule ruleB, ParseRule untilTerminator, Boolean flatten)
   at Ink.InkParser.StatementsAtLevel(StatementLevel level)
   at Ink.InkParser.Parse()
   at Ink.Compiler.Compile()
   at Ink.CommandLineTool..ctor(String[] args)
   at Ink.CommandLineTool.Main(String[] args)

**Comment by joningold** [comment]
So to track this down you need to look at the ink you’ve written; they’ll
be a mistake somewhere that the compiler can’t handle. Try undoing what
you’ve recently done and see if you can pin it down.

Jon

**Comment by zyq0825** [comment]
Thanks for your quick reply. Yes, I figured it out eventually. I was trying to use the if/else format to my conditional text but somehow it didn't work ...

**Comment by Woffelson** [comment]
Opened the software on Ubuntu Linux 18.04 Inky 0.11.0
When empty, prints the following:

Sorry, the ink compiler crashed ☹

Here is some diagnostic information:

Unhandled Exception:
System.TypeLoadException: Could not load type 'Ink.InkParser' from assembly 'ink_compiler, Version=1.0.7096.20672, Culture=neutral, PublicKeyToken=null'.
  at Ink.CommandLineTool..ctor (System.String[] args) [0x001e4] in <926b1e70daa14762b3685e3d8b3c65be>:0 
  at Ink.CommandLineTool.Main (System.String[] args) [0x00001] in <926b1e70daa14762b3685e3d8b3c65be>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'Ink.InkParser' from assembly 'ink_compiler, Version=1.0.7096.20672, Culture=neutral, PublicKeyToken=null'.
  at Ink.CommandLineTool..ctor (System.String[] args) [0x001e4] in <926b1e70daa14762b3685e3d8b3c65be>:0 
  at Ink.CommandLineTool.Main (System.String[] args) [0x00001] in <926b1e70daa14762b3685e3d8b3c65be>:0 
Can't find custom attr constructor image: /home/user/Public/Inky-linux-x64/resources/app.asar.unpacked/main-process/ink/ink_compiler.dll mtoken: 0x0a000001 due to Could not load file or assembly or one of its dependencies. assembly:System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type: type> member:
