### ISSUE TITLE
IOException: Invalid parameter on Linux

### ISSUE THREAD

**Issue by premek** [inkle/inky#77]
I am getting the excetion below for any input text in Inky on Linux. 
It was quite a pain to get it working (install all wine, .net etc) so I hope i did it right. 
However running the compiler from commandline like this works fine: 
```
./resources/app.asar.unpacked/main-process/ink/inklecate_win.exe -ck -o /tmp/o ~/prog/pink/test/choices.ink 
```

```
Sorry, the ink compiler crashed ☹

Here is some diagnostic information:

err:eventlog:ReportEventW L"Application: inklecate_win.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.IO.IOException\nStack:\n   at System.IO.__Error.WinIOError(Int32, System.String)\n   at System.IO.__Error.WinIOError()\n   at System.Console.se"...

Unhandled Exception: 
Ink compiler had an unexpected error ☹

System.IO.IOException: Invalid parameter.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.Console.set_OutputEncoding(Encoding value)
   at Ink.CommandLineTool..ctor(String[] args)
   at Ink.CommandLineTool.Main(String[] args)
wine: Unhandled exception 0xe0434352 in thread 9 at address 0x7b83ae1c (thread 0009), starting debugger...
Ink compiler had an unexpected error ☹

err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Unhandled exception: 0xe0434352 in 32-bit code (0x7b83ae1c).

Register dump:

CS:0023 SS:002b DS:002b ES:002b FS:006b GS:0063

EIP:7b83ae1c ESP:0032eff4 EBP:0032f078 EFLAGS:00000212( - -- I -A- - )

EAX:7b827985 EBX:00000010 ECX:0032f020 EDX:0032f0e4

ESI:00000000 EDI:00128d00

Stack dump:

0x0032eff4: 00128d00 79208fca 74866fd8 00000000

0x0032f004: 00cbc898 00000000 e0434352 00000001

0x0032f014: 00000000 7b83ae1c 00000005 80070057

0x0032f024: 00000000 00000000 00000000 79140000

0x0032f034: 00000059 0032f054 7919c5d4 00000059

0x0032f044: 00000000 0032f0e4 003624b0 02000059

000d: sel=006f base=00000000 limit=00000000 16-bit --x

Backtrace:

=>0 0x7b83ae1c in kernel32 (+0x2ae1c) (0x0032f078)

1 0x791cac08 in clr (+0x8ac07) (0x0032f118)

2 0x791cae41 in clr (+0x8ae40) (0x0032f1d8)

3 0x036b3928 (0x0032f228)

4 0x036b3583 (0x0032f234)

5 0x036b3195 (0x0032f268)

6 0x036b2709 (0x0032f29c)

7 0x036b2687 (0x0032f2b4)

8 0x79164a2a in clr (+0x24a29) (0x0032f330)

9 0x79164bcc in clr (+0x24bcb) (0x0032f470)

10 0x79164c01 in clr (+0x24c00) (0x0032f48c)

11 0x79164c21 in clr (+0x24c20) (0x0032f4a4)

12 0x7922ce82 in clr (+0xece81) (0x0032f608)

13 0x7922cf90 in clr (+0xecf8f) (0x0032f870)

14 0x7922cda4 in clr (+0xecda3) (0x0032fd54)

15 0x7922d199 in clr (+0xed198) (0x0032fda8)

16 0x7922d09a in clr (+0xed099) (0x0032fdf4)

17 0x792aaf00 in clr (+0x16aeff) (0x0032fe2c)

18 0x603b55ab in mscoreei (+0x55aa) (0x0032fe38)

19 0x79007f16 in mscoree (+0x7f15) (0x0032fe48)

20 0x79004de3 in mscoree (+0x4de2) (0x0032fe68)

21 0x7b85f80a in kernel32 (+0x4f809) (0x0032fe98)

22 0x7bc8024c (0x0032feb8)

23 0x7bc831ff (0x0032ffa8)

24 0x7bc8022a (0x0032ffc8)

25 0x7bc52c67 (0x0032ffe8)

0x7b83ae1c: addl	$12,%esp

Modules:

Module	Address	Debug info	Name (18 modules)

PE	400000- 43c000	Deferred inklecate_win

PE	5e0d0000-5e17a000	Deferred diasymreader

PE	603b0000-60416000	Export mscoreei

PE	60930000-60940000	Deferred nlssorting

PE	79000000-7904a000	Export mscoree

PE	79060000-7911e000	Deferred msvcr100_clr0400

PE	79140000-797af000	Export clr

PE	79810000-79870000	Deferred clrjit

PE	7b810000-7b9b0000	Export kernel32

PE	7bc10000-7bc14000	Deferred ntdll

PE	7f870000-7f874000	Deferred rpcrt4

PE	7f900000-7f908000	Deferred ole32

PE	7fa20000-7fa24000	Deferred imm32

PE	7fbf0000-7fbf7000	Deferred gdi32

PE	7fd00000-7fd3b000	Deferred user32

PE	7fe50000-7fe58000	Deferred shlwapi

PE	7fed0000-7fed4000	Deferred advapi32

PE	7ffd0000-7ffd4000	Deferred version

Threads:

process tid prio (all id:s are in hex)

00000008 (D) Z:\home\premek\downloads\Inky-linux-x64\resources\app.asar.unpacked\main-process\ink\inklecate_win.exe

0000002d 2

0000002c 0

00000009 0 <==

0000000e services.exe

00000024 0

00000023 0

0000001c 0

00000010 0

0000000f 0

0000001a winedevice.exe

00000022 0

0000001f 0

0000001e 0

0000001b 0

00000020 plugplay.exe

00000026 0

00000025 0

00000021 0

00000030 explorer.exe

00000034 0

00000033 0

00000032 0

00000031 0

System information:

Wine build: wine-1.8.5 (Debian 1.8.5-1)

Platform: i386

Version: Windows 7

Host system: Linux

Host version: 4.7.0-1-amd64
```

**Comment by lunarcloud** [comment]
This issue is very old and is likely an issue with the way mono was installed on his system. 
Recommend closure.
